# Generated by Django 3.2.9 on 2021-11-16 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiquity', models.CharField(max_length=20, null=True)),
                ('key_ent_fed', models.CharField(max_length=5)),
                ('curp', models.CharField(max_length=18)),
                ('date_of_entry', models.DateField(max_length=12, null=True)),
                ('num_employee', models.CharField(max_length=6)),
                ('nss', models.CharField(max_length=11)),
                ('position', models.CharField(max_length=50)),
                ('salary_base', models.CharField(max_length=8, null=True)),
                ('salary_diary', models.CharField(max_length=8, null=True)),
                ('unionized', models.CharField(max_length=2, null=True)),
                ('rfc', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=10, null=True)),
                ('phone2', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=60)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
