# Generated by Django 3.2.9 on 2021-11-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='key_ent_fed',
        ),
    ]
