# Generated by Django 3.2.9 on 2021-11-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_key_ent_fed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='employee',
        ),
    ]
